from aiogram.dispatcher.filters.state import StatesGroup, State

class CategoryState(StatesGroup):
    choose_command = State()
    category_uz = State()
    category_ru = State()
    category_en = State()
    show_category = State()

class QuestionState(StatesGroup):
    question1 = State()
    answers1 = State()
    correct_answer1 = State()
    question2 = State()
    answers2 = State()
    correct_answer2 = State()
    question3 = State()
    answers3 = State()
    correct_answer3 = State()
    question4 = State()
    answers4 = State()
    correct_answer4 = State()
    question5 = State()
    answers5 = State()
    correct_answer5 = State()
    question6 = State()
    answers6 = State()
    correct_answer6 = State()
    question7 = State()
    answers7 = State()
    correct_answer7 = State()
    question8 = State()
    answers8 = State()
    correct_answer8 = State()
    question9 = State()
    answers9 = State()
    correct_answer9 = State()
    question10 = State()
    answers10 = State()
    correct_answer10 = State()
    show_question = State()